name: Main Validate on master
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate code
        env:
          PY_VERSION: ${{ matrix.python-version }}

        uses: ./.github/actions/validation
